### ISSUE TITLE
Add virtualenv and conda instructions to README

### ISSUE THREAD

**Issue by Iain-S** [alan-turing-institute/bio-Turing-Way#29]
We should add some pre-install instructions to the README that specify how to 

1. make a new conda env
2. or make a new venv env
3. and check your Python version is 3.8

Optionally, we could also add a FAQ/common-problems section on how to diagnose installation problems.

**Comment by myyong** [comment]
This is complete [here](https://github.com/alan-turing-institute/bio-Turing-Way/blob/deploy/pathways/documentation/userguide.md)
