### ISSUE TITLE
Need a different title/logo for each edition

### ISSUE THREAD

**Issue by LydiaFrance** [alan-turing-institute/bio-Turing-Way#7]
When within an edition, e.g. DSG Edition, the logo and title of that Jupyter Book will be indistinguishable from the main/master Turing Way. Instead we want the title to say "Turing Way for DSG" (for example). 

To solve this, we need to have the config file change at the same point the toc file is created.

**Comment by myyong** [comment]
The current pathways implementation no longer deploys separate books. We will not have different config files, which would have enabled this feature.
