### ISSUE TITLE
Pages not on the whitelist are produced in the editions

### ISSUE THREAD

**Issue by LydiaFrance** [alan-turing-institute/bio-Turing-Way#9]
Currently, pages not on the whitelist for each edition still exist in the edition if you type the url directly:

`turingway/editions/newbie/advanced.html`

However this page will not appear in the search, it does not appear in the chapter list, the navigation buttons will not work with it. 

We thought that a line in the config file should prevent this, but it doesn't seem to currently. This may be a useful work around for https://github.com/alan-turing-institute/bio-Turing-Way/issues/8 but does have the disadvantage of unnecessary html files in the directory. 

May need to provide a "clean up" function to remove any html pages that shouldn't exist based on the toc file.

**Comment by myyong** [comment]
Current implementation for pathways will not have this problem.
